### ISSUE TITLE
Interested in joining in on this

### ISSUE THREAD

**Issue by lax1n** [UiO-Gaming/uiogaming.no#29]
Hei / Hi,

I was wondering if it was possible to join in on this project. I know html/css/js/react/python/rails/ruby/express/postgresql/sql/..more and love coding in general.

I'd love to help set something up for upcoming/previous events such as a gallery of pictures, scoreboards/leadersboards, prices (if any? pizza? :D). Can assist with anything really, but this project seems like an awesome place to connect with like minded people.

Happy to have a chat if interested! I'm currently taking a masters degree in entrepreneurship at ifi, but have a degree in IT already.

**Comment by LBlend** [comment]
Hei

Svarer på norsk siden jeg føler meg mest komfortabel med det. 

Vi hadde satt veldig pris på om du vil være med på å utvikle nettsiden! For øyeblikket er det bare jeg som har jobbet med den og designet alt på egenhånd. Jeg synes dermed at det er fint med litt ulike perspektiver og hjelp til å utvikle nye ideer.

Jeg jobber foreløpig på en branch hvor jeg skriver hele nettsiden på nytt. Nettsidens kode er i skrivende stund mildt sagt disgusting og det er mye som ikke er ferdig enda. Derfor har jeg valgt å gjøre det. Denne branchen er ikke publisert enda, men jeg vil gjøre det så snart jeg har fått ryddet opp i det lille jeg har. 

Fremover har jeg valgt å dele backend og frontend i to forskjellige repositories. Dermed vil dette bli repoet for frontend og så vil vi lage et nytt repo for backend (sanity). Repoet vil også med dette bytte navn.

Jeg kommer til å legge deg til i vår utviklings-chat på Discord og invitere deg til organisasjonen på Github om du er interessert.
