### ISSUE TITLE
Blog post images are cropped

### ISSUE THREAD

**Issue by LBlend** [UiO-Gaming/uiogaming.no#33]
When creating a blog post, the main image may be cropped. This is due to it being too big or having a weird aspect ratio.

A solution to fix or mitigate the issue should be considered

**Comment by hs-07** [comment]
@LBlend 
I had resolved this issue, plz assign me the issue

**Comment by LBlend** [comment]
> @LBlend I had resolved this issue, plz assign me the issue

https://github.com/UiO-Gaming/uiogaming.no/issues/37#issuecomment-1148628360
