### ISSUE TITLE
Blog cards aren't stretched in overview

### ISSUE THREAD

**Issue by LBlend** [UiO-Gaming/uiogaming.no#34]
Cards should ideally be the same height regardless of content

**Comment by LBlend** [comment]
See #35

**Comment by hs-07** [comment]
Hey! @LBlend 
I had resolved this issue on my local , assign me this issue so that i could commit changes
![Screenshot 2022-06-07 173155](https://user-images.githubusercontent.com/87127387/172374257-246158c6-9fb1-4e58-b86f-35c070f201cb.png)

**Comment by LBlend** [comment]
> Hey! @LBlend I had resolved this issue on my local , assign me this issue so that i could commit changes ![Screenshot 2022-06-07 173155](https://user-images.githubusercontent.com/87127387/172374257-246158c6-9fb1-4e58-b86f-35c070f201cb.png)

https://github.com/UiO-Gaming/uiogaming.no/issues/37#issuecomment-1148628360
