### ISSUE TITLE
Link overflow in blog overview

### ISSUE THREAD

**Issue by LBlend** [UiO-Gaming/uiogaming.no#35]
The link container is larger than the card itself which causes some issues. For one the text is highlighted in red, which should not be the case. Second, you can click outside of the card and still access the blogpost

![image](https://user-images.githubusercontent.com/24893890/130378381-29334538-a897-4533-9970-72526e244788.png)

**Comment by LBlend** [comment]
See #34

**Comment by hs-07** [comment]
Assign me this issue

**Comment by LBlend** [comment]
> Assign me this issue

https://github.com/UiO-Gaming/uiogaming.no/issues/37#issuecomment-1148628360
